# Site settings
title:       ternary code
email:       ondrej.kosatka@gmail.com
author:      Ondrej Kosatka
description: "there are 10 types of people in this world, those who understand binary and those who dont"
baseurl:     ""
url:         "http://okosatka.github.io"

# Google analytics
google_analytics: UA-59748602-1

theme:
  title: Type Theme
  avatar:
  gravatar: 73aa622075dee50b7e410efc9c699405

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: ondrejkosatka

# Social icons
show_social_icons: true
github_username: okosatka
stackoverflow_id: 324140
twitter_username: ondrejkosatka
google_plus_id: +OndřejKošatka
linkedin_username: ondrejkosatka
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
